version: '3.4'

services:
  webapp:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: bestpost-backend-container
    image: bestpost-backend-image:latest
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8080:80
      - 4343:443
    